#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00

# run the unique val computation
singularity exec docker://brainlife/afni:latest ./parc_to_masksDir_AFNI.sh

#extract the masks
singularity exec docker://brainlife/mrtrix3:3.0.3 ./masks_from_uniqueValsTXT_MRtrix.sh

#run fsl probtrackx2
singularity exec docker://brainlife/fsl:6.0.4-patched2 ./run_ProbtrackX_connectome.sh
